version: "3.9"

services:

  vendure:
    build:
      context: .
      dockerfile: Dockerfile
    image: vendure-image
    container_name: vendure
    volumes:
      - ./vendure:/app/vendure
    depends_on:
      - database
    ports:
      - 3000:3000
      - 4200:4200
    environment:
      DB: postgres
      PG_USER: pguser
      PG_PASS: mysecretpassword
      PG_HOST: database
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=vendure"
      - "traefik.port=3000"
  
  traefik:
    image: traefik:v2.9
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files/traefik.toml:/etc/traefik/traefik.toml
    depends_on:
      - database
      - vendure
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"

  database:
    image: postgres:14.1-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: mysecretpassword