version: "3.9"

services:

  vendure:
    build:
      context: .
      dockerfile: Dockerfile
    image: vendure-image
    container_name: vendure
    volumes:
      - ./vendure:/app/vendure
    depends_on:
      - database
    ports:
      - 3000:3000
      - 4200:4200
    environment:
      DB: postgres
      PG_USER: pguser
      PG_PASS: mysecretpassword
      PG_HOST: database
  
  traefik:
    image: traefik:v2.9
    container_name: traefik
    volumes:
      - ./files/traefik.toml:/etc/traefik/traefik.toml
    depends_on:
      - database
      - vendure
    ports:
      - 8080:8080
      - 80:80

  database:
    image: postgres:14.1-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: mysecretpassword